In [1]:
%matplotlib inline

%install_ext https://raw.github.com/cpcloud/ipython-autotime/master/autotime.py
%load_ext autotime

Installed autotime.py. To use it, type:
  %load_ext autotime


In [2]:
import pyprind

from IPython.display import HTML


import numpy as np
from numpy import genfromtxt

import pandas as pd
from pandas import DataFrame
from pandas import Panel

import warnings

# import sklearn as skl
# #from sklearn.preprocessing import normalize
# from sklearn.cross_validation import KFold
# from sklearn.ensemble import RandomForestClassifier as RFC
# from sklearn.tree import DecisionTreeClassifier as DTC
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.preprocessing import OneHotEncoder

import scipy.io as sio
from scipy.spatial import distance

from scipy.misc import imread, imsave, imresize
from scipy.io import savemat, loadmat
import matplotlib.pyplot as plt

import theano

import keras
from keras.models import *
from keras.layers import *
from keras.layers.recurrent import *
from keras.utils.np_utils import to_categorical
from keras.optimizers import SGD

import pybrain
from pybrain.tools import *
from pybrain.tools import neuralnets as nn

time: 7.76 s


Using Theano backend.


In [3]:
warnings.filterwarnings('ignore')

time: 1 ms


In [5]:
Michael = pd.read_csv('Trials/Michael.csv', header=None)

Michael.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation', 'Label']

Brooke = pd.read_csv('Trials/Brooke.csv', header=None)

Brooke.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                  'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation']

Mark = pd.read_csv('Trials/Mark.csv', header=None)

Mark.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation', 'Label']

Mark.shape

(2072, 11)

time: 66.5 ms


In [6]:
Test_x = pd.read_csv('Trials/results.csv', header=None)

Test_x.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation']

Test_x['Label'] = 1



time: 15.5 ms


In [7]:
temp = Test_x.values

test_X = temp[:, 0:9]

test_Y = temp[:, 10]

test_Y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

time: 21 ms


In [8]:
temp_Y = pd.Series(test_Y)

temp_Y = pd.get_dummies(temp_Y)

test_Y = temp_Y.values

temp2 = np.zeros((len(test_Y), 2))

test_Y = np.concatenate((test_Y, temp2), axis=1)

time: 6.5 ms


In [9]:
Brooke['Label'] = 3

Brooke.shape

(1801, 11)

time: 12.5 ms


In [10]:
Michael = Michael[Michael['Label'] == 1]

Michael_prime = Michael[Michael['Attention'] > 0]

Michael = Michael_prime[Michael_prime['Meditation'] > 0]


Mark_prime = Mark[Mark['Attention'] > 0]

Mark = Mark_prime[Mark_prime['Meditation'] > 0]

Mark.shape

(2072, 11)

time: 29 ms


In [11]:
Mark.head()

Delta   Theta  Low_Alpha  High_Alpha  Low_Beta  High_Beta  Low_Gamma  \
0   160084   26918      11728        7755      3846       2365       1191   
1   840783   93268      11747       65774     99985      21266      40141   
2  1217192  143461      10210       11761     23137      12823       9761   
3  1030498  172887      24678        9847      9626      12134       5483   
4   612621   51515       1114       10179      9506       4846       3245   

   High_Gamma  Attention  Meditation  Label  
0        1494          1          84    NaN  
1       17742          1          84      2  
2        7286          1          84      2  
3        2068          7          88      2  
4        3569          7          75      2

time: 36.5 ms


In [12]:
frames = [Michael.dropna()[0:1800], Mark.dropna()[0:1800], Brooke.dropna()[0:1800]]

data = pd.concat(frames, copy=False, ignore_index=True)

data = data.drop_duplicates()

data = data.dropna()

#data = data.values

time: 39.3 ms


In [13]:
data.shape

(5400, 11)

time: 3 ms


In [14]:
#THIS IS WHAT YOU FIX

# frames = {'Subject 1': Michael[0:1800],
#          'Subject 2': Mark[0:1800],
#          'Subject 3': Brooke[0:1800]}

# data = Panel.from_dict(frames)

# data.shape

time: 8.5 ms


In [15]:
data = data.dropna()

data.shape

(5400, 11)

time: 15 ms


In [16]:
data = data.values

time: 5.5 ms


In [17]:
X = data[:, 0:9]

Y = data[:, 10]

time: 12.5 ms


In [18]:
Y = pd.Series(Y)

Y = pd.get_dummies(Y)

Y = Y.values

time: 6.51 ms


In [19]:
# data = np.concatenate((X, Y), axis=1)

# np.shape(data)

time: 8 ms


In [20]:
# Y = to_categorical(Y.astype(int), 3)

#np.shape(Y)

time: 3 ms


In [21]:
#a = Input(shape=(5400,12))
#b = Dense(3)(a)

mlp_model = Sequential()

mlp_model.add(Dense(64, input_dim=9, init='uniform'))
mlp_model.add(Activation('tanh'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(64, init='uniform'))
mlp_model.add(Activation('tanh'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(3, init='uniform'))
mlp_model.add(Activation('softmax'))

sgd = SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

mlp_model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

time: 9.38 s


In [22]:
#mlp_model.fit(X, Y, batch_size=16, nb_epoch=200, verbose=0)

time: 1.5 ms


In [23]:
results = []


for i in np.arange(0, 10):
    mlp_model.fit(X, Y, batch_size=16, nb_epoch=200, verbose=0)
    
    predicted = mlp_model.predict(test_X, batch_size=20)
    
    temp = np.mean(predicted, axis=0)
    
    results.append(temp)

results = np.asarray(results)

np.mean(results, axis=0)

array([ 0.32733286,  0.36250553,  0.31016161])

time: 11min 25s


In [24]:
results

array([[ 0.03028324,  0.07002434,  0.89969241],
       [ 0.17640946,  0.46194816,  0.36164236],
       [ 0.36589101,  0.45477954,  0.17932946],
       [ 0.46520236,  0.38602215,  0.14877549],
       [ 0.04809855,  0.27456078,  0.67734069],
       [ 0.04632832,  0.88042992,  0.07324175],
       [ 0.3337925 ,  0.57069003,  0.09551748],
       [ 0.30931519,  0.20770191,  0.48298293],
       [ 0.73458499,  0.15268986,  0.11272515],
       [ 0.76342297,  0.16620862,  0.07036839]])

time: 3.5 ms


In [25]:
mlp_model = Sequential()

mlp_model.add(Dense(64, input_dim=9, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(64, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(3, init='uniform'))
mlp_model.add(Activation('softmax'))

sgd = SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

mlp_model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

time: 234 ms


In [26]:
results = []


for i in np.arange(0, 10):
    mlp_model.fit(X, Y, batch_size=16, nb_epoch=200, verbose=0)
    
    predicted = mlp_model.predict(test_X, batch_size=20)
    
    temp = np.mean(predicted, axis=0)
    
    results.append(temp)

results = np.asarray(results)

np.mean(results, axis=0)

array([ 0.,  0.,  1.])

time: 12min 12s


In [27]:
results

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])

time: 4.5 ms


In [28]:
Test_x = pd.read_csv('Trials/results2.csv', header=None)

Test_x.columns = ['Delta', 'Theta', 'Low_Alpha', 'High_Alpha', 'Low_Beta', 'High_Beta',
                         'Low_Gamma', 'High_Gamma', 'Attention', 'Meditation']

Test_x['Label'] = 2

temp = Test_x.values

test_X = temp[:, 0:9]

test_Y = temp[:, 10]

test_Y

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.])

time: 23 ms


In [29]:


mlp_model = Sequential()

mlp_model.add(Dense(64, input_dim=9, init='uniform'))
mlp_model.add(Activation('tanh'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(64, init='uniform'))
mlp_model.add(Activation('tanh'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(3, init='uniform'))
mlp_model.add(Activation('softmax'))

sgd = SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

mlp_model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

time: 240 ms


In [30]:
results = []


for i in np.arange(0, 10):
    mlp_model.fit(X, Y, batch_size=16, nb_epoch=200, verbose=0)
    
    predicted = mlp_model.predict(test_X, batch_size=20)
    
    temp = np.mean(predicted, axis=0)
    
    results.append(temp)

results = np.asarray(results)

np.mean(results, axis=0)

array([ 0.45459535,  0.28768759,  0.25771706])

time: 10min 27s


In [31]:
results

array([[ 0.68016702,  0.1725923 ,  0.14724071],
       [ 0.69085956,  0.01097539,  0.29816505],
       [ 0.17573737,  0.69668925,  0.12757337],
       [ 0.65233445,  0.18125626,  0.16640928],
       [ 0.77927357,  0.03876575,  0.18196067],
       [ 0.1990097 ,  0.67149138,  0.12949888],
       [ 0.08609671,  0.31479222,  0.59911108],
       [ 0.38103536,  0.11907849,  0.49988616],
       [ 0.22605185,  0.58548349,  0.18846466],
       [ 0.67538792,  0.08575133,  0.23886077]])

time: 3.5 ms


In [32]:
mlp_model = Sequential()

mlp_model.add(Dense(64, input_dim=9, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(64, init='uniform'))
mlp_model.add(Activation('relu'))
mlp_model.add(Dropout(0.5))
mlp_model.add(Dense(3, init='uniform'))
mlp_model.add(Activation('softmax'))

sgd = SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

mlp_model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

time: 205 ms


In [33]:
results = []


for i in np.arange(6, 34, 2):
    mlp_model.fit(X, Y, batch_size=i, nb_epoch=200, verbose=0)
    
    predicted = mlp_model.predict(test_X, batch_size=20)
    
    temp = np.mean(predicted, axis=0)
    
    results.append(temp)

results = np.asarray(results)

np.mean(results, axis=0)

array([ 1.,  0.,  0.])

time: 18min 11s


In [34]:
results

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

time: 11.5 ms


In [35]:
data_dim = 9
timesteps = 1800
nb_classes = 3
batch_size = 32

# expected input data shape: (batch_size, timesteps, data_dim)
lstm_model = Sequential()
lstm_model.add(LSTM(32, return_sequences=True,
                    input_shape=(timesteps, data_dim)))  # returns a sequence of vectors of dimension 32
lstm_model.add(Dropout(0.5))
lstm_model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
lstm_model.add(Dropout(0.5))
lstm_model.add(LSTM(9, return_sequences=False))  # return a single vector of dimension 32
lstm_model.add(Dropout(0.5))
#lstm_model.add(LSTM(32, return_sequences=False))
#lstm_model.add(Reshape((3, None)))
lstm_model.add(Dense(3, init='uniform', activation='softmax'))
#lstm_model.add(Flatten())


lstm_model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
lstm_1 (LSTM)                    (None, 1800, 32)      5376        lstm_input_1[0][0]               
____________________________________________________________________________________________________
dropout_9 (Dropout)              (None, 1800, 32)      0           lstm_1[0][0]                     
____________________________________________________________________________________________________
lstm_2 (LSTM)                    (None, 1800, 32)      8320        dropout_9[0][0]                  
____________________________________________________________________________________________________
dropout_10 (Dropout)             (None, 1800, 32)      0           lstm_2[0][0]                     
___________________________________________________________________________________________

In [36]:
lstm_model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])


time: 17.5 ms


In [37]:
lstm_model.fit(X, Y, batch_size=64, nb_epoch=20, verbose=1)

Exception: Error when checking model input: expected lstm_input_1 to have 3 dimensions, but got array with shape (5400, 9)

time: 44 ms
